name = "LoVe"
defaultTargets = ["LoVe"]

[leanOptions]
autoImplicit = false
linter.unusedVariables = false 
# linter.unusedTactic = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.10.0"

[[require]]
name = "autograder" 
git = "https://github.com/qiaochloe/lean4-autograder-main" 
rev = "7b389cac593fa1881f07916ff9818b208a958eef"


[[lean_lib]]
name = "LoVe"
